//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripTask
    {
        public int TripTaskID { get; set; }
        public Nullable<int> TripID { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<System.DateTime> TaskDueDate { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
